"""
DOCUMENT GENERATION SKILL
Real artifacts, generated by tools -- not screenshots or plain text.
  - generate_invoice_pdf: Jinja2 HTML -> WeasyPrint -> GST-correct PDF.
  - generate_analysis_deck: python-pptx with native chart objects
    (not embedded matplotlib images) built from analytics data.
"""
import os
from datetime import datetime

from jinja2 import Environment, FileSystemLoader
from pptx import Presentation
from pptx.chart.data import CategoryChartData
from pptx.enum.chart import XL_CHART_TYPE
from pptx.util import Inches, Pt
from weasyprint import HTML

import config
from db import Bill, Product, SessionLocal
from tools.analytics import get_sales_range, get_daily_summary

TEMPLATE_DIR = os.path.join(os.path.dirname(__file__), "..", "templates")


def generate_invoice_pdf(bill_id):
    """Render a finalized bill as a clean, GST-correct PDF invoice."""
    session = SessionLocal()
    try:
        bill = session.get(Bill, bill_id)
        if not bill:
            return {"error": f"No bill with id {bill_id}."}
        if bill.status != "finalized":
            return {"error": "Only a finalized bill can be invoiced. "
                              "Finalize it first."}

        items = []
        for it in bill.items:
            product = session.get(Product, it.product_id)
            items.append({
                "product": it.product_name_snapshot,
                "hsn_code": product.hsn_code if product else None,
                "qty": it.qty, "unit_price": it.unit_price,
                "gst_rate": it.gst_rate, "cgst_amt": it.cgst_amt,
                "sgst_amt": it.sgst_amt, "line_total": it.line_total,
            })

        env = Environment(loader=FileSystemLoader(TEMPLATE_DIR))
        template = env.get_template("invoice.html")
        html_str = template.render(
            shop_name=config.SHOP_NAME, shop_address=config.SHOP_ADDRESS,
            shop_gstin=config.SHOP_GSTIN, bill_id=bill.id,
            date=(bill.finalized_at or datetime.utcnow()).strftime("%d %b %Y, %I:%M %p"),
            customer=bill.customer.name if bill.customer else None,
            payment_mode=bill.payment_mode, payment_ref=bill.payment_ref,
            items=items, subtotal=bill.subtotal, cgst=bill.cgst,
            sgst=bill.sgst, total=bill.total,
        )

        out_path = os.path.join(config.INVOICE_DIR, f"invoice_bill_{bill.id}.pdf")
        HTML(string=html_str).write_pdf(out_path)
        return {"success": True, "bill_id": bill.id, "file_path": out_path}
    finally:
        session.close()


def _add_title_slide(prs, title, subtitle):
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = title
    slide.placeholders[1].text = subtitle
    return slide


def _add_bar_chart_slide(prs, title, categories, values, series_name):
    slide = prs.slides.add_slide(prs.slide_layouts[5])
    slide.shapes.title.text = title
    chart_data = CategoryChartData()
    chart_data.categories = categories
    chart_data.add_series(series_name, values)
    slide.shapes.add_chart(
        XL_CHART_TYPE.COLUMN_CLUSTERED, Inches(0.7), Inches(1.5),
        Inches(8.6), Inches(5), chart_data,
    )
    return slide


def _add_line_chart_slide(prs, title, categories, values, series_name):
    slide = prs.slides.add_slide(prs.slide_layouts[5])
    slide.shapes.title.text = title
    chart_data = CategoryChartData()
    chart_data.categories = categories
    chart_data.add_series(series_name, values)
    slide.shapes.add_chart(
        XL_CHART_TYPE.LINE_MARKERS, Inches(0.7), Inches(1.5),
        Inches(8.6), Inches(5), chart_data,
    )
    return slide


def _add_pie_chart_slide(prs, title, categories, values, series_name):
    slide = prs.slides.add_slide(prs.slide_layouts[5])
    slide.shapes.title.text = title
    chart_data = CategoryChartData()
    chart_data.categories = categories
    chart_data.add_series(series_name, values)
    slide.shapes.add_chart(
        XL_CHART_TYPE.PIE, Inches(1.5), Inches(1.5),
        Inches(6), Inches(5), chart_data,
    )
    return slide


def _add_bullets_slide(prs, title, bullets):
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = title
    body = slide.placeholders[1].text_frame
    body.clear()
    for i, b in enumerate(bullets):
        p = body.paragraphs[0] if i == 0 else body.add_paragraph()
        p.text = b
        p.font.size = Pt(18)
    return slide


def generate_analysis_deck(start_date, end_date, period_label=None):
    """
    Build a PPTX analysing the store between start_date and end_date
    (YYYY-MM-DD): sales trend, top items, payment split, stock health,
    GST collected. All charts are native pptx chart objects, not images.
    """
    label = period_label or f"{start_date} to {end_date}"
    daily = get_sales_range(start_date, end_date)["daily_totals"]

    session = SessionLocal()
    try:
        from db import DailyClose
        closes = session.query(DailyClose).filter(
            DailyClose.date >= start_date, DailyClose.date <= end_date,
        ).all()
        total_tax = round(sum(c.tax_collected for c in closes), 2)
        total_cash = round(sum(c.cash_total for c in closes), 2)
        total_upi = round(sum(c.upi_total for c in closes), 2)
        total_card = round(sum(c.card_total for c in closes), 2)
        total_credit = round(sum(c.credit_total for c in closes), 2)

        from tools.inventory import get_low_stock
        low_stock = get_low_stock()["low_stock"]
    finally:
        session.close()

    combined_top = {}
    for d in daily:
        day_summary = get_daily_summary(d["date"])
        for item in day_summary["top_items"]:
            combined_top[item["product"]] = combined_top.get(item["product"], 0) + item["revenue"]
    top_sorted = sorted(combined_top.items(), key=lambda kv: kv[1], reverse=True)[:6]

    prs = Presentation()

    _add_title_slide(prs, f"{config.SHOP_NAME} — Sales Analysis", label)

    total_sales = round(sum(d["total"] for d in daily), 2)
    _add_bullets_slide(prs, "Headline Numbers", [
        f"Total sales: ₹{total_sales}",
        f"GST collected (CGST+SGST): ₹{total_tax}",
        f"Cash: ₹{total_cash}   UPI: ₹{total_upi}   Card: ₹{total_card}   Credit: ₹{total_credit}",
        f"SKUs at/below reorder level: {len(low_stock)}",
    ])

    if daily:
        _add_line_chart_slide(
            prs, "Daily Sales Trend",
            [d["date"] for d in daily], [d["total"] for d in daily], "Sales (₹)",
        )

    if top_sorted:
        _add_bar_chart_slide(
            prs, "Top Selling Items (by revenue)",
            [name for name, _ in top_sorted], [round(v, 2) for _, v in top_sorted],
            "Revenue (₹)",
        )

    if total_cash + total_upi + total_card + total_credit > 0:
        _add_pie_chart_slide(
            prs, "Payment Mode Split",
            ["Cash", "UPI", "Card", "Credit"],
            [total_cash, total_upi, total_card, total_credit], "₹",
        )

    if low_stock:
        _add_bullets_slide(
            prs, "Reorder Needed",
            [f"{p['name']}: {p['stock_qty']} {p['unit']} left "
             f"(reorder at {p['reorder_level']})" for p in low_stock[:8]],
        )

    fname = f"analysis_{start_date}_to_{end_date}.pptx".replace(":", "-")
    out_path = os.path.join(config.DECK_DIR, fname)
    prs.save(out_path)
    return {"success": True, "file_path": out_path, "period": label,
            "total_sales": total_sales, "total_tax": total_tax}
